services:

  enrollment:
    build: ./enrollment
    image: cip-enrollment:latest
    networks: [cip_services]

  sessions:
    build: ./sessions
    image: cip-sessions:latest
    networks: [cip_services]

  claims:
    build: ./claims
    image: cip-claims:latest
    networks: [cip_services]

  fraud:
    build: ./fraud-detection
    image: cip-fraud:latest
    environment:
      KAFKA_BROKERS: redpanda:9092
    networks: [cip_services]

  projection:
    build: ./projection
    image: cip-projection:latest
    environment:
      PORT: "3000"
      MONGODB_URI: mongodb://mongo:27017/cip_projection
      KAFKA_BROKERS: redpanda:9092
    networks: [cip_services]

  bff:
    build: ./bff
    image: cip-bff:latest
    environment:
      PORT: "3001"
      MONGODB_URI: mongodb://mongo:27017/cip_projection
      CLAIMS_URL: http://claims:8083
      SESSIONS_URL: http://sessions:8082
    ports:
      - "3001:3001"
    depends_on:
      - projection
    networks: [cip_services]

  # workbench:
  #   build: ../web/clinic-workbench
  #   image: cip-workbench:latest
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - bff
  #   networks: [cip_services]

networks:
  cip_services:
    name: cip
    external: true
